# Generated by Django 4.2.7 on 2024-02-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
