# Generated by Django 4.2.7 on 2024-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='is_company',
            field=models.BooleanField(default=True, verbose_name='company status'),
        ),
        migrations.AddField(
            model_name='usergraduate',
            name='is_graduate',
            field=models.BooleanField(default=True, verbose_name='graduate status'),
        ),
    ]
