# Generated by Django 4.2.7 on 2024-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usercompany_is_company_usergraduate_is_graduate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='usergraduate',
            name='is_graduate',
        ),
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='company status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_graduate',
            field=models.BooleanField(default=False, verbose_name='graduate status'),
        ),
    ]
