# Generated by Django 4.2.7 on 2024-02-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_comments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercompany', verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usergraduate', verbose_name='Выпускник'),
        ),
    ]
