# Generated by Django 4.2.7 on 2024-02-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_comments_username_author_alter_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='username_graduate',
        ),
    ]
