# Generated by Django 4.2.7 on 2024-02-25 12:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
        ('users', '0015_rename_username_comments_username_graduate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTecher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(max_length=150, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_image', verbose_name='Изображение пользователя')),
                ('post', models.CharField(max_length=150, null=True, verbose_name='Должность')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='graduates.departments', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Пользователь_преподаватель',
                'verbose_name_plural': 'Пользователи_преподаватели',
                'db_table': 'user_teacher',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
