# Generated by Django 4.2.7 on 2024-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
        ('users', '0016_usertecher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTecher',
            new_name='UserTeacher',
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='teacher status'),
        ),
    ]
