# Generated by Django 4.2.7 on 2024-02-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
        ('users', '0017_rename_usertecher_userteacher_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.departments', verbose_name='Кафедра'),
        ),
    ]
