# Generated by Django 4.2.7 on 2024-03-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_usercompany_company_alter_usergraduate_company'),
    ]
