# Generated by Django 4.2.7 on 2024-03-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_graduates_company'),
        ('users', '0023_remove_usercompany_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.companies', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='usergraduate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.companies', verbose_name='Компания'),
        ),
    ]
