# Generated by Django 4.2.7 on 2024-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_comments_options_alter_usergraduate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergraduate',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Карьерные достижения'),
        ),
        migrations.AddField(
            model_name='usergraduate',
            name='post',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
    ]
