# Generated by Django 4.2.7 on 2024-04-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_usergraduate_achievements_usergraduate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergraduate',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки'),
        ),
    ]
