# Generated by Django 4.2.7 on 2024-04-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0016_statuses'),
        ('users', '0027_usergraduate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergraduate',
            name='status_of_working',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.statuses', verbose_name='Статус'),
        ),
    ]
