# Generated by Django 4.2.7 on 2024-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название модели')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'db_table': 'feedback',
            },
        ),
    ]
