# Generated by Django 4.2.7 on 2024-04-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0016_statuses'),
        ('feedback', '0002_remove_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Описание')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.companies', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Форма для добавления описания компании',
                'verbose_name_plural': 'Формы для добавления описания компании',
                'db_table': 'feedbackcompany',
            },
        ),
    ]
