# Generated by Django 4.2.7 on 2024-04-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedbackgraduate_delete_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedbackgraduate',
            table='feedbackgraduate',
        ),
    ]
