# Generated by Django 4.2.7 on 2024-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedbackgraduate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='')),
                ('description', models.TextField(blank=True, max_length=120, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'db_table': 'feedback',
            },
        ),
        migrations.DeleteModel(
            name='FeedBackGraduate',
        ),
    ]
