# Generated by Django 4.2.7 on 2024-04-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_usergraduate_status_of_working'),
        ('feedback', '0009_feedbackgraduate_delete_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcompany',
            options={'verbose_name': 'Форма братной связи для компаний', 'verbose_name_plural': 'Формы братной связи для компаний'},
        ),
        migrations.AlterModelOptions(
            name='feedbackgraduate',
            options={'verbose_name': 'Форма обратной связи для выпускников', 'verbose_name_plural': 'Формы обратной связи для выпускников'},
        ),
        migrations.AlterField(
            model_name='feedbackgraduate',
            name='graduate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usergraduate', verbose_name='Выпускник'),
        ),
    ]
