# Generated by Django 4.2.7 on 2024-04-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_remove_contact_first_name_remove_contact_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
