# Generated by Django 4.2.7 on 2024-04-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_remove_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email'),
        ),
    ]
