# Generated by Django 4.2.7 on 2024-04-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='theme',
            field=models.TextField(default='Здравствуйте! Примите, пожалуйста, участие в нашем опросе!', max_length=100, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Текст письма'),
        ),
    ]
