# Generated by Django 4.2.7 on 2024-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_contact_theme_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Текст письма'),
        ),
    ]
