# Generated by Django 4.2.7 on 2024-02-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_choice_text_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
