# Generated by Django 4.2.7 on 2024-02-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userteacher_department'),
        ('polls', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='username_graduate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usergraduate', verbose_name='Выпускник'),
        ),
    ]
