# Generated by Django 4.2.7 on 2024-02-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userteacher_department'),
        ('polls', '0006_remove_choice_username_graduate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='username_graduate',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='polls.choice', verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос')),
                ('username_graduate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usergraduate', verbose_name='Выпускник')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'ОТветы студента',
                'db_table': 'answers',
            },
        ),
    ]
