# Generated by Django 4.2.7 on 2024-02-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_question_username_graduate_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Оnветы студента'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.choice', verbose_name='Вариант ответа'),
        ),
    ]
