# Generated by Django 4.2.7 on 2024-02-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_answer_options_remove_answer_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
    ]
