# Generated by Django 4.2.7 on 2024-03-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_answer_options_answer_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('choice_text',), 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
