# Generated by Django 4.2.7 on 2024-04-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_choice_options_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('id',), 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_percent',
            field=models.FloatField(default=0, verbose_name='Процент голосов'),
        ),
    ]
