# Generated by Django 4.2.7 on 2024-03-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_usercompany_company_usergraduate_company'),
        ('polls_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Вариант ответа')),
                ('votes', models.IntegerField(default=0, verbose_name='Количество голосов')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_company.question_company', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'db_table': 'choices_company',
            },
        ),
        migrations.CreateModel(
            name='Answer_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls_company.choice_company', verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_company.question_company', verbose_name='Вопрос')),
                ('username_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercompany', verbose_name='Представитель компании')),
            ],
            options={
                'verbose_name': 'Ответ представителя компании',
                'verbose_name_plural': 'Ответы представителей компаний',
                'db_table': 'answers_company',
            },
        ),
    ]
