# Generated by Django 4.2.7 on 2024-04-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_company', '0003_alter_choice_company_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice_company',
            options={'ordering': ('id',), 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
    ]
