# Generated by Django 4.2.7 on 2024-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_company', '0004_alter_choice_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice_company',
            name='choice_percent',
            field=models.FloatField(default=0, verbose_name='Процент голосов'),
        ),
    ]
