# Generated by Django 4.2.7 on 2024-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('adress', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('longitude', models.CharField(max_length=150, unique=True, verbose_name='Широта')),
                ('latitude', models.CharField(max_length=150, unique=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
    ]
