# Generated by Django 4.2.7 on 2024-03-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_companies'),
    ]
