# Generated by Django 4.2.7 on 2024-03-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_alter_graduates_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='adress',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='latitude',
            field=models.CharField(max_length=150, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='longitude',
            field=models.CharField(max_length=150, verbose_name='Широта'),
        ),
    ]
