# Generated by Django 4.2.7 on 2024-03-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_alter_companies_adress_alter_companies_latitude_and_more'),
    ]

