# Generated by Django 4.2.7 on 2024-03-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_remove_graduates_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduates',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.companies', verbose_name='Текущее место работы'),
        ),
    ]
