# Generated by Django 4.2.7 on 2024-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_graduates_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
