# Generated by Django 4.2.7 on 2024-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0007_companies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
