# Generated by Django 4.2.7 on 2024-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0009_companies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='latitude',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='longitude',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Широта'),
        ),
    ]
