# Generated by Django 4.2.7 on 2024-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0011_rename_adress_companies_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='longitude',
        ),
        migrations.AddField(
            model_name='companies',
            name='coords',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Координаты'),
        ),
    ]
