# Generated by Django 4.2.7 on 2024-03-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0012_remove_companies_latitude_remove_companies_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ('name',), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ('name',), 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='directions',
            options={'ordering': ('name',), 'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'ordering': ('name',), 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ('name',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ('name',), 'verbose_name': 'Направленность(Профиль)', 'verbose_name_plural': 'Направленности(Профили)'},
        ),
    ]
