# Generated by Django 4.2.7 on 2024-04-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0014_statuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
