# Generated by Django 4.2.7 on 2024-04-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0016_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuses',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество выпускников'),
        ),
        migrations.AddField(
            model_name='statuses',
            name='percent',
            field=models.FloatField(default=0.0, verbose_name='Количество выпускников в процентах'),
        ),
    ]
