# Generated by Django 4.2.7 on 2024-04-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0017_statuses_count_statuses_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='is_russia',
            field=models.BooleanField(default=0),
        ),
    ]
