# Generated by Django 4.2.7 on 2024-06-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0019_alter_companies_is_russia'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='graduates.departments', verbose_name='Кафедра'),
        ),
    ]
