# Generated by Django 4.2.7 on 2024-06-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0020_groups_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='graduates.qualifications', verbose_name='Квалификация'),
        ),
    ]
